name: CI/CD Google Play

on:
  push:
    branches: [ master ]

env:
  ossUsername: ${{ secrets.OSSRH_USERNAME }}
  ossPassword: ${{ secrets.OSSRH_PASSWORD }}
  signingKeyId: ${{ secrets.SIGNINGKEYID }}
  signingKeyPassword: ${{ secrets.SIGNINGKEYPASSWORD }}
  signingKey: ${{ secrets.SIGNINGKEY }}
  ONEGRAVITY_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  ONEGRAVITY_OPENSOURCE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  ONEGRAVITY_OPENSOURCE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      # Create a build number based on timestamp / UTC time
      - name: set release date
        run: |
          echo "BUILD_NUMBER=$(date +"%s")" >> ${GITHUB_ENV}

      # Decode the keystore file containing the signing key
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.1
        with:
          fileDir: './secrets'
          fileName: '1gravity.keystore'
          encodedString: ${{ secrets.KEYSTORE_FILE }}

      # Decode the Google Play api key file
      - name: Decode Google Play API key
        id: decode_api_key
        uses: timheuer/base64-to-file@v1.1
        with:
          fileDir: './secrets'
          fileName: 'google-play-api-key.json'
          encodedString: ${{ secrets.GOOGLE_PLAY_API_KEY }}

      # Build bundle and publish to Google Play
      - name: Build & publish to Google Play
        run: ./gradlew
          -PBUILD_NUMBER="${{ env.BUILD_NUMBER }}"
          -PONEGRAVITY_KEYSTORE_FILE="../${{ steps.decode_keystore.outputs.filePath }}"
          -PgooglePlayApiKey="../${{ steps.decode_api_key.outputs.filePath }}"
          publishBundle --max-workers 1 --stacktrace
